* ACSS: AFL Implementation That Outputs ACSS

A new implementation of Audio Formatting Language (AFL) as used in
AsTeR. This implementation wil output strings annotated with ACSS
properties, and make that output available via a socket. When
complete, swapping out the old AFL implementation in AsTeR should give
us a version of AsTeR that module ~emacspeak-maths~ can use.

Fri Oct 21 15:35:27 PDT 2016
** AFL Exported Symbols:

(loop for s being the external-symbols of (find-package "AFL") collect
s)

(AFL:*GLOBAL-AUDIO-STATE* AFL:MINIMUM-VALUE AFL:RICHNESS AFL:*SOUND-PRIORITY*
 AFL:URSULA AFL:*GLOBAL-SPEECH-STATE* AFL:SCALE-BY AFL:KID
 AFL:DEFINE-STANDARD-VOICE AFL:INTERROGATIVE AFL:*READER-COMMA-PAUSE*
 AFL:MULTI-MOVE-TO AFL:GENERALIZED-AFL-OPERATOR AFL:SWITCH
 AFL:MAKE-AUDIO-FILENAME AFL:*PRONOUNCE-IGNORE-CASE-IN-TEXT*
 AFL:DEFINE-MINIMUM-VALUE AFL:MAXIMUM-VALUE AFL:VOICE AFL:RIGHT-VOLUME
 AFL:WITH-SURROUNDING-PAUSE AFL:QUICKNESS AFL:SELECT-SOUND
 AFL:*CURRENT-AUDIO-STATE* AFL:LENGTH-OF-SUBINTERVAL AFL:AUDIO-MOVE-TO
 AFL:*ALWAYS-DEHYPHENATE* AFL:SET-PERIOD-PAUSE AFL:*GLOBAL-TOTAL-AUDIO-STATE*
 AFL:PLAY-REPEATEDLY AFL:MULTI-SCALE-BY AFL:GET-POINT-IN-SPEECH-SPACE
 AFL:SOUND-NAME AFL:RESET-DECTALK AFL:VALUE AFL:PARAGRAPH-BEGIN AFL:NEW-BLOCK
 AFL:DEFINE-FINAL-SCALE-FACTOR AFL:BREATHINESS AFL:HARRY
 AFL:WITH-LAZY-SET-STATE DECTALK:SEND-TEXT AFL:INITIALIZE-AUDIO-SPACE
 AFL:MULTI-MOVE-BY DECTALK:SPEAK-FILE AFL:PAUL AFL:SWITCH-OFF AFL:SMOOTHNESS
 AFL:INTERVAL AFL:GET-FINAL-SCALE-FACTOR DECTALK:SPEAK-NUMBER-STRING
 AFL:CURRENT-PRONUNCIATION-MODE AFL:SECONDARY-STRESS AFL:SWITCH-ON
 AFL:PRIMARY-STRESS AFL:*CURRENT-TOTAL-AUDIO-STATE* AFL:LOCAL-SET-STATE
 AFL:GET-PRONUNCIATION DECTALK:SHOULD-I-CONTINUE? AFL:PITCH-RANGE AFL:WENDY
 AFL:PAUSE AFL:ID AFL:*GLOBAL-PRONUNCIATION-MODE* AFL:ACTIVATE-SOUND-AUDIO
 AFL:BASELINE-FALL DECTALK:SHOULD-I-STOP? AFL:LOW-INTONATION
 AFL:DEFINE-DEFAULT-VALUE AFL:SET-COMMA-PAUSE AFL:COMMA-INTONATION
 AFL:SAVE-POINT-IN-SPEECH-SPACE AFL:DEFINE-MAXIMUM-VALUE AFL:FRANK
 AFL:*LAZY-SET-STATE* AFL:*PRONUNCIATION-MODE* AFL:*CURRENT-SPEECH-STATE*
 AFL:EXCLAMATORY-STRESS AFL:DEFINE-SYNTHESIZER-CODE AFL:SET-STEP-SIZE
 AFL:MULTI-STEP-BY AFL:INITIALIZE-TOTAL-SPACE DECTALK:*STREAM* AFL:EXIT-BLOCK
 AFL:SPEECH-RATE AFL:SUBCLAUSE-BOUNDARY DECTALK:SEND-SPACE AFL:HIGH-INTONATION
 DECTALK:WITH-FILE-INSTEAD-OF-DECTALK AFL:RE-INITIALIZE-SPEECH-SPACE AFL:PORT
 AFL:RITA AFL:CURRENT-VALUE AFL:TOGGLE-SWITCH AFL:DEACTIVATE-SOUND-AUDIO
 AFL:ADD-DIMENSION AFL:HIGH-LOW-INTONATION DECTALK:WITH-FILE-AS-WELL-AS-DECTALK
 AFL:GLOBAL-SET-STATE AFL:MOVE-BY AFL:VOLUME AFL:LOUDNESS AFL:GET-STEP-SIZE
 AFL:DEFINE-PRONUNCIATION AFL:MOVE-TO AFL:AVERAGE-PITCH AFL:STRESS-RISE
 AFL:AUDIO-PROMPT AFL:SYNCHRONIZE-AND-PLAY DECTALK:AWAIT-SILENCE AFL:DENNIS
 AFL:LEFT-VOLUME AFL:EXCLAMATION AFL:DIMENSION-RANGE AFL:LAX-BREATHINESS
 AFL:REFRESH AFL:*AWAIT-SILENCE-WHEN-USING-STEREO* AFL:NAMED-BLOCK
 AFL:SET-FINAL-SCALE-FACTOR DECTALK:FORCE-SPEECH AFL:STEP-BY
 AFL:PERIOD-INTONATION AFL:BETTY AFL:DEFINE-UNIT-SIZE AFL:LARYNGILIZATION
 AFL:PLAY-ONCE AFL:HEAD-SIZE AFL:DEFINE-STEP-SIZE AFL:COMPUTE-RANGE
 AFL:STEP-SIZE AFL:*READER-PERIOD-PAUSE* AFL:*SOUND-DIR-NAME*
 AFL:*DEFAULT-VOICE* AFL:HAT-RISE AFL:WITH-PRONUNCIATION-MODE
 AFL:INITIALIZE-SPEECH-SPACE AFL:LIST-OF-SPEECH-DIMENSIONS AFL:ASSERTIVENESS)
CL-USER> 
